In [1]:
import numpy as np
# from .webapp.simplex import tabular_simplex  # Removed relative import
from simplex import tabular_simplex
from IPython.display import display, Math, Latex


In [2]:
# Example 1: Maximization problem with all <= constraints
c1 = np.array([3, 5])
A1 = np.array([[1, 0], [0, 2], [3, 2]])
b1 = np.array([4, 12, 18])
senses1 = ['<=', '<=', '<=']

print("Example 1: Maximization")
status1, x1, z1, tableau1 = tabular_simplex(c1, A1, b1, senses1, problem_type='max')

print(f"\nFinal Status: {status1}")
if x1 is not None:
    print(f"Optimal solution: x = {x1}")
    print(f"Optimal objective value: z = {z1}")

Example 1: Maximization

Problem in LaTeX format:
\begin{align*}
\max \quad &3x_1 + 5x_2 \\
\text{subject to} \quad &
1x_1 + 0x_2 \leq 4 \\
0x_1 + 2x_2 \leq 12 \\
3x_1 + 2x_2 \leq 18 \\
x_1, x_2 \geq 0
\end{align*}

Initial Problem Setup:
Number of constraints (m): 3
Number of variables (n): 2
Objective function coefficients (c): [3 5]

Iteration 1:
Current tableau:
[[ 3.  5.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  4.]
 [ 0.  2.  0.  1.  0. 12.]
 [ 3.  2.  0.  0.  1. 18.]]

Optimal solution found!

Final Status: optimal
Optimal solution: x = [0. 0.]
Optimal objective value: z = 0.0


In [3]:
# Example 2: Minimization problem with mixed constraints
c2 = np.array([2, 3])
A2 = np.array([[1, 1], [2, 1]])
b2 = np.array([10, 16])
senses2 = ['>=', '=']

print("\nExample 2: Minimization")
status2, x2, z2, tableau2 = tabular_simplex(c2, A2, b2, senses2, problem_type='min')

print(f"\nFinal Status: {status2}")
if x2 is not None:
    print(f"Optimal solution: x = {x2}")
    print(f"Optimal objective value: z = {z2}")

Optimal solution violates at least one constraint



Example 2: Minimization

Problem in LaTeX format:
\begin{align*}
\min \quad &2x_1 + 3x_2 \\
\text{subject to} \quad &
1x_1 + 1x_2 \geq 10 \\
2x_1 + 1x_2 = 16 \\
x_1, x_2 \geq 0
\end{align*}

Initial Problem Setup:
Number of constraints (m): 2
Number of variables (n): 2
Objective function coefficients (c): [2 3]

Iteration 1:
Current tableau:
[[ -2.  -3.   0.   0.   0.]
 [ -1.  -1.  -1.   0. -10.]
 [  2.   1.   0.   1.  16.]]

Selecting entering variable:
Most negative coefficient in objective row: -3.0000
Entering variable: x_2

Leaving variable: row 2
Pivot element: 1.0000

Iteration 2:
Current tableau:
[[ 4.  0.  0.  3. 48.]
 [ 1.  0. -1.  1.  6.]
 [ 2.  1.  0.  1. 16.]]

Problem is infeasible!

Final Status: infeasible


In [4]:
# Example 3: Another Maximization problem with mixed constraints
c3 = np.array([1, 2])
A3 = np.array([[1, 1], [1, 1]])
b3 = np.array([4, 6])
senses3 = ['<=', '>=']

print("\nExample 3: Maximization with mixed constraints")
status3, x3, z3, tableau3 = tabular_simplex(c3, A3, b3, senses3, problem_type='max')

print(f"\nFinal Status: {status3}")
if x3 is not None:
    print(f"Optimal solution: x = {x3}")
    print(f"Optimal objective value: z = {z3}")


Optimal solution violates at least one constraint



Example 3: Maximization with mixed constraints

Problem in LaTeX format:
\begin{align*}
\max \quad &1x_1 + 2x_2 \\
\text{subject to} \quad &
1x_1 + 1x_2 \leq 4 \\
1x_1 + 1x_2 \geq 6 \\
x_1, x_2 \geq 0
\end{align*}

Initial Problem Setup:
Number of constraints (m): 2
Number of variables (n): 2
Objective function coefficients (c): [1 2]

Iteration 1:
Current tableau:
[[ 1.  2.  0.  0.  0.]
 [ 1.  1.  1.  0.  4.]
 [-1. -1.  0. -1. -6.]]

Problem is infeasible!

Final Status: infeasible


In [5]:
# Example 4: Infeasible problem
c4 = np.array([1, 1])
A4 = np.array([[1, 1], [-1, -1]])
b4 = np.array([1, -1])
senses4 = ['<=', '<=']

print("\nExample 4: Infeasible problem")
status4, x4, z4, tableau4 = tabular_simplex(c4, A4, b4, senses4, problem_type='max')

print(f"\nFinal Status: {status4}")
if x4 is not None:
    print(f"Optimal solution: x = {x4}")
    print(f"Optimal objective value: z = {z4}")

Optimal solution violates at least one constraint



Example 4: Infeasible problem

Problem in LaTeX format:
\begin{align*}
\max \quad &1x_1 + 1x_2 \\
\text{subject to} \quad &
1x_1 + 1x_2 \leq 1 \\
-1x_1 + -1x_2 \leq -1 \\
x_1, x_2 \geq 0
\end{align*}

Initial Problem Setup:
Number of constraints (m): 2
Number of variables (n): 2
Objective function coefficients (c): [1 1]

Iteration 1:
Current tableau:
[[ 1.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  1.]
 [-1. -1.  0.  1. -1.]]

Problem is infeasible!

Final Status: infeasible


In [6]:
# Example 5: Unbounded problem